# Generated by Django 3.0.5 on 2020-04-18 13:29

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Needy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=255)),
                ('introducer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('introducer_number', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField()),
                ('people_count', models.IntegerField()),
                ('priority', models.IntegerField()),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('city', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
