# Generated by Django 3.0.5 on 2020-04-18 13:57

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('najdaapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='needy',
            name='introducer_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
